### ISSUE TITLE
Automatically remove .clix/.env file when open api key is incorrect

### ISSUE THREAD

**Issue by SkobelkinYaroslav** [dgurns/clix#1]
When launching the application after an unsuccessful attempt with an incorrect API key, the application will once again consider the same incorrect key. It would be desirable that upon receiving a 401 error, the .env file gets deleted, prompting the user to re-enter the API key.

**Comment by dgurns** [comment]
hey sorry just seeing this now. Great idea. I added a `make reset` command which will clear out the `~/.clix/.env` file and also remove the existing executable, if present. Try pulling `master` and you should have it.
